config/routes.rb
Rails.application.routes.draw do
  get 'pos', to: 'pos#index'

  resources :stock_categories
  resources :customers

  resources :stocks
  resources :posts
  resources :store_configurations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'stock_categories#index'
end

app/models/stock_category.rb
class StockCategory < ApplicationRecord
end

app/controllers/stock_categories_controller.rb
class StockCategoriesController < ApplicationController
  before_action :set_stock_category, only: [:show, :edit, :update, :destroy]

  # GET /stock_categories
  # GET /stock_categories.json
  def index
    @stock_categories = StockCategory.all
  end

  # GET /stock_categories/1
  # GET /stock_categories/1.json
  def show
  end

  # GET /stock_categories/new
  def new
    @stock_category = StockCategory.new
  end

  # GET /stock_categories/1/edit
  def edit
  end

  # POST /stock_categories
  # POST /stock_categories.json
  def create
    @stock_category = StockCategory.new(stock_category_params)

    respond_to do |format|
      if @stock_category.save
        format.html { redirect_to @stock_category, notice: 'Stock category was successfully created.' }
        format.json { render :show, status: :created, location: @stock_category }
      else
        format.html { render :new }
        format.json { render json: @stock_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stock_categories/1
  # PATCH/PUT /stock_categories/1.json
  def update
    respond_to do |format|
      if @stock_category.update(stock_category_params)
        format.html { redirect_to @stock_category, notice: 'Stock category was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock_category }
      else
        format.html { render :edit }
        format.json { render json: @stock_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_categories/1
  # DELETE /stock_categories/1.json
  def destroy
    @stock_category.destroy
    respond_to do |format|
      format.html { redirect_to stock_categories_url, notice: 'Stock category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_category
      @stock_category = StockCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_category_params
      params.require(:stock_category).permit(:category_name, :quality, :todays_rate, :amount_spent, :weight_in_stock)
    end
end

app/helpers/stock_categories_helper.rb
module StockCategoriesHelper
end

app/views/stock_categories/_form.html.erb
<%= form_for(stock_category) do |f| %>
  <% if stock_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock_category.errors.count, "error") %> prohibited this stock_category from being saved:</h2>

      <ul>
      <% stock_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_name %>
    <%= f.text_field :category_name %>
  </div>

  <div class="field">
    <%= f.label :quality %>
    <%= f.text_field :quality %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stock_categories/edit.html.erb
<h1>Editing Stock Category</h1>

<%= render 'form', stock_category: @stock_category %>

<%= link_to 'Show', @stock_category %> |
<%= link_to 'Back', stock_categories_path %>

app/views/stock_categories/index.html.erb
<div class="todays_rate">
  <% @stock_categories.each do |category| %>
    <% if category.updated_at < Date.today.to_time %>
      <h5>
        <span class="label label-danger">
          You need to enter Today's Rate for <%= category.category_name %>
        </span>
        &nbsp; &nbsp; Last entered on: <%= Time.parse(category.updated_at.to_s).strftime('%d-%b-%Y %I:%M %p') %>
      </h5>
    <% end %>
  <% end %>
</div>
<div id="stock_categories"></div>
<script type="text/javascript" charset="utf-8">
    $(function () {
        window.router = new JewellsApp.Routers.StockCategoriesRouter({stock_categories: <%= @stock_categories.to_json.html_safe %>});
    });
</script>

app/views/stock_categories/new.html.erb
<h1>New Stock Category</h1>

<%= render 'form', stock_category: @stock_category %>

<%= link_to 'Back', stock_categories_path %>

app/views/stock_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category name:</strong>
  <%= @stock_category.category_name %>
</p>

<p>
  <strong>Quality:</strong>
  <%= @stock_category.quality %>
</p>

<%= link_to 'Edit', edit_stock_category_path(@stock_category) %> |
<%= link_to 'Back', stock_categories_path %>