config/routes.rb
Rails.application.routes.draw do
  get 'pos', to: 'pos#index'

  resources :stock_categories
  resources :customers

  resources :stocks
  resources :posts
  resources :store_configurations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'stock_categories#index'
end

app/models/store_configuration.rb
class StoreConfiguration < ApplicationRecord
end

app/controllers/store_configurations_controller.rb
class StoreConfigurationsController < ApplicationController
  before_action :set_store_configuration, only: [:show, :edit, :update, :destroy]

  # GET /store_configurations
  # GET /store_configurations.json
  def index
    @store_configurations = StoreConfiguration.all
  end

  # GET /store_configurations/1
  # GET /store_configurations/1.json
  def show
  end

  # GET /store_configurations/new
  def new
    @store_configuration = StoreConfiguration.new
  end

  # GET /store_configurations/1/edit
  def edit
  end

  # POST /store_configurations
  # POST /store_configurations.json
  def create
    @store_configuration = StoreConfiguration.new(store_configuration_params)

    respond_to do |format|
      if @store_configuration.save
        format.html { redirect_to @store_configuration, notice: 'Store configuration was successfully created.' }
        format.json { render :show, status: :created, location: @store_configuration }
      else
        format.html { render :new }
        format.json { render json: @store_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store_configurations/1
  # PATCH/PUT /store_configurations/1.json
  def update
    respond_to do |format|
      if @store_configuration.update(store_configuration_params)
        format.html { redirect_to @store_configuration, notice: 'Store configuration was successfully updated.' }
        format.json { render :show, status: :ok, location: @store_configuration }
      else
        format.html { render :edit }
        format.json { render json: @store_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store_configurations/1
  # DELETE /store_configurations/1.json
  def destroy
    @store_configuration.destroy
    respond_to do |format|
      format.html { redirect_to store_configurations_url, notice: 'Store configuration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store_configuration
      @store_configuration = StoreConfiguration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_configuration_params
      params.require(:store_configuration).permit(:store_name, :store_desc, :email, :phone, :website, :address, :gstn)
    end
end

app/helpers/store_configurations_helper.rb
module StoreConfigurationsHelper
end

app/views/store_configurations/_form.html.erb
<%= form_for(store_configuration) do |f| %>
  <% if store_configuration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store_configuration.errors.count, "error") %> prohibited this store_configuration from being saved:</h2>

      <ul>
      <% store_configuration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :store_name %>
    <%= f.text_field :store_name %>
  </div>

  <div class="field">
    <%= f.label :store_desc %>
    <%= f.text_area :store_desc %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :gstn %>
    <%= f.text_field :gstn %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/store_configurations/edit.html.erb
<h1>Editing Store Configuration</h1>

<%= render 'form', store_configuration: @store_configuration %>

<%= link_to 'Show', @store_configuration %> |
<%= link_to 'Back', store_configurations_path %>

app/views/store_configurations/index.html.erb
<div id="store_configurations"></div>

<script type="text/javascript" charset="utf-8">
  $(function () {
     window.router = new JewellsApp.Routers.StoreConfigurationsRouter({storeConfigurations: <%= @store_configurations.to_json.html_safe %>});
  });
</script>

app/views/store_configurations/new.html.erb
<h1>New Store Configuration</h1>

<%= render 'form', store_configuration: @store_configuration %>

<%= link_to 'Back', store_configurations_path %>

app/views/store_configurations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store name:</strong>
  <%= @store_configuration.store_name %>
</p>

<p>
  <strong>Store desc:</strong>
  <%= @store_configuration.store_desc %>
</p>

<p>
  <strong>Email:</strong>
  <%= @store_configuration.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @store_configuration.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @store_configuration.website %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store_configuration.address %>
</p>

<p>
  <strong>Gstn:</strong>
  <%= @store_configuration.gstn %>
</p>

<%= link_to 'Edit', edit_store_configuration_path(@store_configuration) %> |
<%= link_to 'Back', store_configurations_path %>